version: '3'

services: 
  api:
    container_name: nestjs
    build: ./nestjs
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./nestjs:/home/node/app

  web:
    container_name: reactjs
    build: ./reactjs
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3000
    volumes:
      - ./reactjs:/home/node/app